### ISSUE TITLE
Website overhaul proposals

### ISSUE THREAD

**Issue by karianna** [AdoptOpenJDK/openjdk-website#237]
I figure this issue can capture some more of the permanent discussion and ideas.

**Strawman I**

https://docs.google.com/drawings/d/1h0b6-5jN5nESo48maZcLctImHcEO0uvMs_qrlKT1nzs/edit?usp=sharing

**Comment by karianna** [comment]
Hi all - I’ve updated “Strawman I” slightly - Is this the sort of thing we want to go for?  If so I can ask our designer to mock this up properly for further discussion

**Comment by tellison** [comment]
I think the design is too cluttered now, and we need a different approach for the website design.  Here's my proposal for a redesign.

## Background

The AdoptOpenJDK website started with a single "big blue button" to keep things really simple about downloading the best JDK to date.  The button links to the latest build for the platform detected by the browser information.

Over time we have grown to include lots more platforms, an archive of previous release and nightly builds, installers, Docker images, etc.  To accommodate these the website has acquired extra buttons and menu options which start to clutter the homepage.  The website user now needs to know a great deal of technical information about what they want as they start to navigate through the pages to find a particular download.

We currently offer seven variants of OpenJDK-based builds, across up to eight or so platforms.  We soon intend to also offer experimental OpenJDK code stream builds, and possibly small footprint builds of each of these!

## Proposal

The proposal is to get back to a simple user experience by using a "recommender" or "digital product advisor" approach.  Users who come to the AdoptOpenJDK website home page will be guided through a set of selections to determine their user profile and intended use for the download.  Based upon this information the website will offer the most appropriate download for the visitors needs.

Over time we can change the recommendations for a user, even where the questions remain the same; for example, if we wish to promote a particular configuration.

There are many examples of this digital product advisor on websites today, helping users to pick the right laptop, coffee flavour, or even dog collar.  See http://www.guided-selling.org/tag/product-advisor/  and http://www.myproductadvisor.com/mpa/base/home.do  In this case we are "selling" a free software download.

## Design

The design falls into two main categories.
 - Determining the usage profile: gathering enough information about the user and their intended usage to be able to make a download recommendation.
 - The visual representation of the information gathering: how we design the user interface to determine the usage profile.

## User profile

Thoughts on how to categorize our website visitors...
 - I'm an application user and just need Java to run Minecraft etc.  I don't really know or care much about it.
 - I'm a sys admin and need to install Java on my server as a default system runtime for people to use.
 - I want to put Java onto my VM running in the cloud.  I want it as a container / Docker image.
 - I am a Java developer and need a JDK with all the development tools, or to put alongside my Java IDE.
 - I want to contribute to the implementation of Java itself.  I know about OpenJDK and need a binary to test.
 - I am an application developer and want to redistribute Java with my application.  I care about footprint and performance, and want to see the trade off of each for my application.
 - I'm a power-user and know exactly what I want, take me straight to the full list of options, and let me quickly filter them by version, platform, VM, etc. easily.

## Visual Representation

The home page should be visually appealing, and lead users through a small number of steps to determine their profile and offer the most appropriate download.

Using pictures and icons is preferable to text, and sliders and wheels to indicate strength of opinion on topics rather than simple "yes" or "no" questions.  Look at some of the examples given on the website above (http://www.guided-selling.org/5-best-product-advisor-examples-of-2015/) to get an idea.

While being mobile friendly is good, bear in mind that Java is typically not downloaded from a mobile device.

**Comment by karianna** [comment]
I agree with doing some Ux requirement gathering, workshops etc on this.  However, the new trend of the guided selling / product advisor is the _opposite_ of what a primarily technical audiences want (it's great for general purpose B2C for sure).  We need to do the user research but I strongly suspect the majority of users will have at least some technical know how and will most likely be Java developers and will therefore want the minimum of clicks (drop off opportunities) to get their Adopt Binary.  As an aside I'll drag in jClarity's Web Ux person who was instrumental in figuring this stuff out for our audience (software developers).  So I guess the first question we nee dto answer is "who's the dominant user?"

**Comment by karianna** [comment]
I'm afraid not, we're still battling the last few build and infra issues on 11 and 8 releases before turning our eyes on this.

**Comment by karianna** [comment]
We are no longer enhancing this legacy website.  Please see the adoptium.net website.
