### ISSUE TITLE
Releases(Archive) are in the wrong order

### ISSUE THREAD

**Issue by pshipton** [AdoptOpenJDK/openjdk-website#342]
https://adoptopenjdk.net/archive.html?variant=openjdk8&jvmVariant=openj9

The releases are in backwards order. Older releases are shown first, but the latest release should be first.

**Comment by SeanC1083** [comment]
@pshipton I think the issue is that based on the current design of the page title and the way that the interactions/selectors govern the page view. To correct the flow between pages there should be three tabs - one for each separate page. If there were three tabs, the tab that the user is on will be highlighted and so they will naturally click one of the other two to change the page view. **Having said that, we are working on some new design ideas that should resolve this issue and improve the user experience.**
