### ISSUE TITLE
Windows Installation Path Instruction Modification

### ISSUE THREAD

**Issue by ChrisKibble** [AdoptOpenJDK/openjdk-website#390]
On the Installation Page for Windows, the documentation states that to change the path you execute **set PATH=%cd%\jdk-11.0.1+13\bin;%PATH%**.  This will only change the path for the current session - as soon as the terminal window is closed, you'll have lost that change.  Recommend changing this to either using SETX (on versions of Windows that support it) or modifying the variable through system setting.

**Comment by ParkerM** [comment]
It looks like using `setx` to set the path can be destructive due to a 1024 character limit (see [this post](https://superuser.com/questions/387619/overcoming-the-1024-character-limit-with-setx)).

An alternative option could be to use Powershell commands, but it looks like the documented solutions only mention how to persist path changes for new Powershell sessions. I think this is because Windows environment variables are stored in the registry, which _can_ technically be edited through Powershell by invoking .NET libraries or directly updating registry values. In either case I don't think there's any built-in one-liners that don't rely on helper scripts or third-party tools.

The [Powershell docs](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_environment_variables?view=powershell-6#changing-environment-variables) suggest changing env vars through the system settings GUI. Same with Oracle's help page [How do I set or change the PATH system variable?](https://www.java.com/en/download/help/path.xml).

I imagine most users would select the MSI installers once they become available (see [openjdk-installer/issues/27](https://github.com/AdoptOpenJDK/openjdk-installer/issues/27)), which would remove the manual step for updating path. Power users or users who would otherwise prefer a binary archive would likely understand the path requirements, so perhaps the message could then be removed or made more generic for Windows archives (e.g. "Add `bin` directory to path").

**Comment by lootkips** [comment]
I would suggest the first method which will create a persistent system path variable:  This is a method I use as just making a new path will delete the regkeys for existing system paths:  Guide here:
https://peter.hahndorf.eu/blog/AddingToPathVariable.html
https://github.com/hahndorf/hacops/blob/master/Set-PathVariable.ps1
