### ISSUE TITLE
Should be referencing hosted versions of 3rd party .js libraries

### ISSUE THREAD

**Issue by Joe-Brady** [AdoptOpenJDK/openjdk-website#4]
Moment.js, asciinema-player.js, asciinema-player.css, asciicast-107176.json

These files should not be hosted on our repository if possible.

Need to search for these files on a hosted location, such as Cloudflare.

**Comment by Joe-Brady** [comment]
Moment.js changed to be cloudflare version.

All 'asciinema' files have been removed. Temporarily commented out the line of HTML in getinvolved.html.

@gdams is working on getting the video hosted on the asciinema site, so that we can embed it.

**Comment by Joe-Brady** [comment]
@gdams @a-roberts 

This issue could be closed, and a new one opened for the asciinema content being hosted, as described above?

**Comment by gdams** [comment]
Sgtm

**Comment by tellison** [comment]
> These files should not be hosted on our repository if possible.

Just to expand on this...  the intention is to ensure there is no ambiguity about licensing / ownership of the website code.  If we simply reference the third-party libs then it is quite clear.

However, if it turns out that there is a negative performance impact, or the external hosting sites are not reliable, etc then we can look at alternative approaches to keep things clear.

**Comment by Joe-Brady** [comment]
@tellison  This is already complete, I will close to avoid confusion.

There is no negative performance impact from what I can see so far.

The only remaining question is whether George and Adam want to use the asciinema player - if yes, then they will need to have that hosted by asciinema, as we're discussing here.
