### ISSUE TITLE
Broken links in the nightly webpage

### ISSUE THREAD

**Issue by spoole167** [AdoptOpenJDK/openjdk-website#52]
On this page.  https://adoptopenjdk.net/nightly.html    there are a lot of links that end up as a 404

Release links don’t work  
Change log links don’t work
Commit links don’t work

**Comment by Joe-Brady** [comment]
Hi, the changelog and commit links have been removed in the currently open PR (see staging.adoptopenjdk.net). They will be re-added at a later date, and there are work items open for this.

The release links have been fixed in the same PR.

I will close this issue, but please re-open if there's something I haven't addressed.
