### ISSUE TITLE
Should have both release and snapshot JMC RCP builds

### ISSUE THREAD

**Issue by thegreystone** [AdoptOpenJDK/openjdk-website#595]
Right now only the snapshot builds are available on the JMC download page. Both release builds and snapshot builds should be available.

That said, this work should only be done once #594 is completed, as the final JMC RCP release builds need to override the update site URL to point to the final location of the build of update site for the same version.

See:
https://twitter.com/johanjanssen42/status/1187004997571137538

**Comment by aahlenst** [comment]
Adding `https://adoptopenjdk.jfrog.io/adoptopenjdk/p2-jmc/` or `https://adoptopenjdk.jfrog.io/adoptopenjdk/p2-jmc-releases/` (whatever you like best) would do it? You could then publish the JMC releases there. Or is something else needed?

**Comment by johanjanssen** [comment]
Releases should also have a version such as JDKMissionControl 7. That way I can create Chocolatey packages for them including checking the hash. Now all releases have the same resulting artifact, but different hashes which makes it very difficult to maintain. Next to that some people prefer to have a specific version instead of the latest.

**Comment by thegreystone** [comment]
Right - for releases it would be nice to add the version in the name of the verified release bundles, and simplify the bundle names a bit.

Here's what some other distributions do:
Liberica:
http://download.bell-sw.com/lmc/bellsoft-lmc7.0-windows-amd64.zip
Azul:
https://static.azul.com/zmc/bin/zmc7.0.0.49-ca-win_x64.zip

How about going with something similarly clean and simple? jmc7.0.0-win-x64.zip?
