### ISSUE TITLE
Inconsistencies in look and feel of the download pages

### ISSUE THREAD

**Issue by sxa** [AdoptOpenJDK/openjdk-website#629]
Ref discussion in https://adoptopenjdk.slack.com/archives/C5LU29BC3/p1573055920018800 we seem to have three different formats for our download pages - main releases, archive and nightlies all look inconsistent. I'm not sure why the main release page was changed, but that one seems (at least to m) to be the messiest of the three (Supposedly it's a design "more closely resembling what designers think good UX is)

Latest releases page:

![image](https://user-images.githubusercontent.com/6487691/70143537-d5ba9580-1693-11ea-88ab-1678df43398a.png)

Archive page:

![image](https://user-images.githubusercontent.com/6487691/70143598-fd116280-1693-11ea-87b0-f355ff0b6509.png)

Nightlies page:

![image](https://user-images.githubusercontent.com/6487691/70143631-19ad9a80-1694-11ea-9059-fcef18beb091.png)

Also as per #628 the redesign of the main latest releases page (The one you get from the "other platforms" link on the main page) has lost the docker links during the redesign.

**Comment by sharon-wang** [comment]
Chiming in 🙂 

Being able to filter by OS and Architecture would be a nice feature not only on the "Latest release" page, but also the "Archive" and "Nightly builds" pages.

The "Nightly builds" page does have the search box, but I actually didn't notice it until I recently realized it wasn't a button 😅. I think the centered text in the search box is what made me think it was a button. Perhaps left-aligning the input box and the hint text and adding an ellipsis might be a quick solution to making it look more like an input field:
![Untitled 3](https://user-images.githubusercontent.com/25834218/83074776-b861f500-a040-11ea-959e-7c5d7aa9e3cd.png)
This does look a bit off since everything on the page is centered.

Although, as mentioned in this issue it would be nice to have a more unified experience across each of these pages. That way, a user can easily filter/search through the builds on any of the pages without having to switch their behaviour.

**Comment by karianna** [comment]
We're working on the new website at Adoptium.net
