### ISSUE TITLE
Permanent URLs to the latest releases

### ISSUE THREAD

**Issue by dmpe** [AdoptOpenJDK/openjdk-website#733]
Hi, 
[amazon java](https://docs.aws.amazon.com/corretto/latest/corretto-11-ug/downloads-list.html)  has a lovely feature of having a permanent URL which redirects to always the latest release. Can this project please also consider it?
My case is particularly on windows where we automate a lot of stuff using ansible and having a permanent URL which I can use to download e.g LTS releases would be very welcome. 
It makes it much easier to deploy. In fact, I wouldn't want to switch to amazon jdk because of `silent` installation which AdopJDK has much better support for. 
Thanks

**Comment by aahlenst** [comment]
We have something like that: https://api.adoptopenjdk.net/v3/installer/latest/8/ga/windows/x64/jdk/hotspot/normal/adoptopenjdk?project=jdk gives you the latest Windows x64 MSI for 8. Please see https://api.adoptopenjdk.net/swagger-ui/#/Installer/get_v3_installer_latest__feature_version___release_type___os___arch___image_type___jvm_impl___heap_size___vendor_ for the full docs.

Discovering this requires expert knowledge. We should improve our website in order to make things like that easier to discover.

**Comment by tellison** [comment]
See also #669 for similar request

**Comment by karianna** [comment]
@johnoliver - Is this resolved with the v3 API?

**Comment by utkarshvishnoi11** [comment]
Hey I am beginner here,Can anyone suggest something to contribute in?

**Comment by karianna** [comment]
> Hey I am beginner here,Can anyone suggest something to contribute in?

Please join our adoptium.net/slack channel :-)

**Comment by irfan-ra** [comment]
Are there a permanent link to download different version for Linux? For example latest version of OpenJDK 19: OpenJDK19U-jdk_x64_linux_hotspot_19_36.tar.gz

**Comment by tellison** [comment]
Have a look at https://api.adoptium.net/q/swagger-ui/
