### ISSUE TITLE
Add translations of our website, add Localize to Sponsors

### ISSUE THREAD

**Issue by gdams** [AdoptOpenJDK/openjdk-website#79]
We should add google web translate to our website to help get maximum exposure. Setup is easy to do [here](https://translate.google.com/manager/website/) and then we can edit the translations where necessary to make them as accurate as possible. I will put together a table of languages that people can perhaps sign up to work on tidying up the translations. Please stick your name in if you think that you are proficient enough to correctly translate the page/ add a new language.

|Language|User|
|---|---|
|French| |
|German| |
|Spanish| |
|Chinese| @gibfahn |
|Portuguese| @allandequeiroz|

**Comment by Joe-Brady** [comment]
In progress, although I'm not sure how much control we have over the actual translations with this system? I.e. none at all from what I can see?

I'm still a big fan of its simplicity though, and would prefer that in the long term instead of having to forever keep on top of translation improvements.

**Comment by Joe-Brady** [comment]
Closing, as this solution is included in part of the current PR.
But please re-open or create a new issue if there are improvements to be made.

**Comment by allandequeiroz** [comment]
Why not portuguese?

**Comment by tellison** [comment]
@allandequeiroz because we don't know anybody who speaks Portuguese and can check / fix the translation for us.

If you know Portuguese well and are willing to review the automatic Google translation for us that would be wonderful.

**Comment by gdams** [comment]
@allandequeiroz I am looking for other languages to add, I'll add Portuguese to the table if you are happy to help us support that?

**Comment by allandequeiroz** [comment]
@tellison  @gdams I can help with that, sure.

**Comment by Joe-Brady** [comment]
Portuguese added on staging.

**Comment by Joe-Brady** [comment]
Removed translations temporarily while we work out the contributions aspect

**Comment by Joe-Brady** [comment]
After some thought and experimentation, it seems that the 'easy options', such as this Google translation website add-on, are not going to work for us. Unless I've missed something, it seems that Google's offering removed the contributions feature back in 2015 (according to a few threads on various forums), but never really documented this properly or removed the feature cleanly - the service looks like it should work, but doesn't.

**If somebody knows otherwise, or can suggest a very close equivalent to the Google solution, then that would be great!**

Instead, we looked at doing this 'the proper way' with a `locales` directory and multiple versions of the site.

However, this also appears to be problematic and not particularly scaleable/maintainable - what if someone changes the layout of the English version of a page? Now, all of the other languages have to manually apply this change as well, and try not to miss anything.

I'm currently looking into other approaches. All suggestions welcome!

**Comment by allandequeiroz** [comment]
I really didn't read it yet but sounds that maybe bing offers something like that.
https://msdn.microsoft.com/en-us/library/dn341983.aspx

**Comment by Joe-Brady** [comment]
I've had a look at the Bing solution - it seems that managing contributions is still very difficult (I couldn't work out how it worked after several hours of trying), but if someone can understand it where I couldn't, then great.

Let's pause the search for a few days - we are contacting https://localizejs.com/ to see if they are able to help.

**Comment by gibfahn** [comment]
This issue was discussed for Node.js in https://github.com/nodejs/nodejs.org/issues/972#issuecomment-303208008, and one of the proposed solutions was https://gitlocalize.com/. I haven't looked into it extensively, but the way it works seems pretty solid (the service raises PRs into your docs repo).

**Comment by Joe-Brady** [comment]
@gibfahn That looks like a potential backup plan, thank you - however, Localize.js is currently in touch with us and will likely be providing their service in exchange for being added as a sponsor. Their translation system looks very, very good, and is able to translate live, dynamic websites (like ours) where the actual content is coming from all sorts of sources that aren't just Markdown, including Handlebars files and auto-generated stuff from Javascript.

**Comment by sotayamashita** [comment]
@gibfahn I appreciate you introducing our service. :bow: :100:

@Joe-Brady 

>  (snip) sources that aren't just Markdown, including Handlebars/HTML files and auto-generated stuff from Javascript.  (snip)

Hi, I am an engineer of GitLocalize. Is there any example of docs file?

**Comment by Joe-Brady** [comment]
Hi @sotayamashita, thanks for getting in touch and for your interest in the project - probably the best idea is to, for example, have a look at `/src/js/releases.js` in this repo.

One line to look at as an example is:
`htmlArray[objIndex].binaryBlock = ("<div...`

There is some hard-coded text, but other text is inserted on page load, the content source being a JSON file in another repo. The latter will change daily in some cases.

So it's not quite as simple as if we had static `.md` files (or similar). The advantage that we found with Localize.js is that their system works by translating the live, built page, so it doesn't matter where the content comes from, how it appears on the page, or how often the content changes. The translation process itself begins with machine translation, then allows for teams of human translators to work on improving phrases etc.

From my initial look at GitLocalize, it appears to be a fantastic solution, but more suited to static content that isn't generated on page load? If I'm off the mark, please let me know! Thanks again for your interest :-)
