### ISSUE TITLE
Update Migration Guide and document that we're not going to bundle any fonts

### ISSUE THREAD

**Issue by aahlenst** [AdoptOpenJDK/openjdk-website#799]
See https://github.com/AdoptOpenJDK/openjdk-support/issues/70 for context.

**Comment by hendrikebbers** [comment]
From my point of view this will be a good first issue once the blog post is online (https://github.com/AdoptOpenJDK/blog/issues/498). Otherwise it will be quite hard to understand for a newcomer. @aahlenst can you ping me once the post is online. I will transform this issue in a "good first issue" afterwards.

**Comment by kki03** [comment]
Hi, since 11.0.10 the Freetype library is not bundled anymore and I doubt that the relicensed Lucida fonts will be shipped in the future. Instead it should be noted that Freetype and FontConfig are required to successfully run Eclipse Adoptium.
