### ISSUE TITLE
Review and Update the Release Notes page

### ISSUE THREAD

**Issue by smlambert** [AdoptOpenJDK/openjdk-website#866]
There have been assorted issues with requests to improve our release notes information.  There is additionally a desire to automate some of the information, as we release frequently and leaving the release notes updates as a manual step for a release champion is onerous.

This issue means to review the [current release notes page](https://adoptopenjdk.net/release_notes.html) and the process by which it is updated and make a plan for improving both.

There has been discussion around pulling the release info from JIRA directly and doing a pretty printed version on the Adopt website.  We can also use this issue to discuss potential hurdles to doing this, and ways to improve the experience of navigating to the notes from other parts of the website (related: https://github.com/AdoptOpenJDK/openjdk-website/issues/604).

**Comment by adamfarley** [comment]
Adam's work:
- Step 1: Gather list of resources available to us. Stylesheets, mailing list message + link, etc.
- Step 2: Complete MVP. Take mailing list message and feed it into stylesheet. Auto-generate PR via github action, triggered by comments in issues?
- Step 3: Gather some feedback. Draw up plans for further development.

Resources:
- Mailing list email example for release notes source: Lost the link. 1 minute.
- Issue covering request for release notes per build: https://github.com/AdoptOpenJDK/openjdk-website/issues/604
- Release automation epic-ish issue: https://github.com/AdoptOpenJDK/TSC/issues/178
- Github workflow yml example: https://github.com/AdoptOpenJDK/openjdk-tests/blob/master/.github/workflows/autoTestPR.yml

**Comment by aahlenst** [comment]
To save you some time, what I could find out in past endeavors...

Our current process:

1. Find someone with a JBS account (OpenJDK author status or better).
2. Nag them until they give in. If they don't, GOTO 1.
3. Make them run a query like https://bugs.openjdk.java.net/browse/JDK-8253813?jql=project%20%3D%20JDK%20AND%20fixVersion%20%3D%2011.0.9%20ORDER%20BY%20created%20DESC while being logged into JBS.
4. Copy and paste the output and format it.
5. Create a PR.

Why so complicated? If you look at the [announcement for 11.0.9](https://mail.openjdk.java.net/pipermail/jdk-updates-dev/2020-October/004007.html), there are security issues like [JDK-8237990](https://bugs.openjdk.java.net/browse/JDK-8237990) that are not accessible if you aren't logged in and therefore not returned by the search. The aren't included in https://builds.shipilev.net/backports-monitor/release-notes-11.0.9.txt either (an often cited example of an automatically generated changelog); at least I'm not able to find them.

https://community.atlassian.com/t5/Jira-questions/how-to-export-to-csv/qaq-p/175115 explains how to export as CSV. I also found https://github.com/maxandersen/botty interesting as an example to create a GitHub bot.

Recently, we linked to Foojay (https://foojay.io/java-15/?quarter=102020&tab=highlights). Someone said that they pull in changes to Oracle JDK, too, which would be bad because there are changes/backports that only end up in Oracle JDK or come into OpenJDK at a later date. I haven't checked it myself, however.

BTW: My perfectionsm doesn't like the term release notes for what we've been doing so far. That's an automatically generated change log. Having release notes somewhere else than only in the blog or including changes applied to AdoptOpenJDK would be great, too, but we can save those enhancements for a future issue.

**Comment by adamfarley** [comment]
Good news is that I already have author status, but there's something decidedly questionable about using an author login to give author-or-above information to non-authors. Especially when it comes to security bugs.

Thanks for the rest of the information. I'll be sure to avoid OracleJDK changesets, and I'll consult Max's repo if a GitHub bot turns out a better idea than a GitHub action (unless they turn out to be the same thing).

**Comment by aahlenst** [comment]
> but there's something decidedly questionable about using an author login to give author-or-above information to non-authors.

While you have a point there, the release announcements on the OpenJDK mailing lists and Foojay both reveal that information after the version has been released. But they only reference the title and bug number while omitting the details. Foojay only links to the CVE database (https://foojay.io/java-11/?quarter=092020&tab=cve).

I'm not arguing for a specific approach (yet), only providing information about past attempts to tackle the release notes.

**Comment by adamfarley** [comment]
> I'm not arguing for a specific approach (yet), only providing information about past attempts to tackle the release notes.

Fair enough. Thanks for filling me in on all that. :)

**Comment by adamfarley** [comment]
Notes:
 
*Plan*
Person writes "generate release notes for 11.0.9" command in a TSC issue.
A github action generates a back-end release notes file for that release.
A PR is created to merge the file. (See "Create Pull Request" in autoTestPR.yml in openjdk-tests for an example of how to do this.)

Note: Right now the Github action prototype force-pushes into Adam Farley's staged branch, as he wanted to rapidly prototype changes without creating a hundred PRs. Requires a deploy private key repository secret with write permissions for the push repo.

*Design Concept*
One release_notes page - Shows the latest release notes per release, in a twisty each.
One release_notes_archive page - Shows a big list of release notes for each release, in twisties.
Several back-end files, one per release, containing the release notes for that release, html-formatted.
(Note: seperate back-end files adds complexity, but does prevent merge conflicts as the PRs won't overlap except for the link to the import file.)

The idea is that the release_notes page identifies the latest back-end file per major release, and populates itself accordingly.
The archive page could be the same page, except disabling the "filter" that limits the display to only the latest release.
Advise using javascript, like the kind for the adoptopenjdk index page that populates the html. 
https://www.jotform.com/blog/html5-imports-import-html-files-into-html-files-83467/
Basically, the javascript for the release_notes page should contain an array of the html files containing release notes, updated by the github action.
Javascript appears to have issues identifying "all files in a directory" on the server-side, so this list is necessary.

*Potential Release Note sources*
- Andrew Hughes:
  - Release notes: http://pkgs.devel.redhat.com/cgit/rpms/java-1.8.0-openjdk/tree/NEWS?h=private-gnu_andrew-rhel-7.9-vanilla
  - Contact: Adam Farley emailed Andrew on the 14th of January.
  - Response: No response
- Red Hat OpenJDK Documentation Team: 
  - https://access.redhat.com/documentation/en-us/openjdk/11/
  - Source: currently Redhat-internal
  - Contact. Emailed POC oin the 14th of January. POC says we can c+p the team's work as long as we mention Red Hat is the source.
  - POC is Red Hat internal. Adam Farley can get messages to them, or can ask if they're happy to liaise directly.
  - Pros: Already neatly formatted, mostly what we want, easy win.
  - Cons: These docs are for the OpenJDK on RHEL, which is different from upstream OpenJDK (as spelled out in Chapter 2). We'd need to edit our copy of the docs.
- IBM OpenJDK Documentation team for OpenJ9:
    - e.g. https://github.com/eclipse/openj9/tree/master/doc/release-notes
    - Pros: They're happy for us to link or copy.
	- Cons: These are generated manually, and some aspects may contain references to foojay.
- Foojay 
  - https://foojay.io/java-8/?quarter=102020&tab=allissues
  - Current 3rd party release notes provider
- OpenJDK Mailing List
  - https://mail.openjdk.java.net/pipermail/jdk-updates-dev/2020-October/004007.html
  - Pay especial attention to the "Live versions" links, as they are both handy.
  - Pros: Basic text, easy to copy, URLs are simple to reference as they use basic version strings.
  - Cons: Basic text, and lots of it. We'd have to format it ourselves.
  - Note: Shipilev's link is likely the best source for an MVP, as we know it's exclusively OpenJDK, the link is less unabiguous about the version string than the bitly one, and it's easy to copy.

**Comment by smlambert** [comment]
This issue should be addressed by the website-adoptium work so removing from Top Priorities project.

**Comment by karianna** [comment]
Work being done at adoptium.net
